version: "3.3"
services:
  extension_bug:
    image: node:14.15.4
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    volumes:
      - ./extension_bug:/usr/src/app

  cache_bug:
    image: node:14.15.4
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    volumes:
      - ./cache_bug:/usr/src/app

  postgres:
    image: arousseau/postgres-replication:12.3
    environment:
      POSTGRES_USER: arousseau
      POSTGRES_PASSWORD: password
      REPLICATION_USER: arousseau_rep
      REPLICATION_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432

  postgres-slave:
    image: arousseau/postgres-replication:12.3
    links:
      - postgres
    environment:
      POSTGRES_USER: arousseau
      POSTGRES_PASSWORD: password
      REPLICATION_USER: arousseau_rep
      REPLICATION_PASSWORD: password
      REPLICATION_ROLE: slave
      POSTGRES_MASTER_SERVICE_HOST: postgres
    expose:
      - 5432
    depends_on:
      - postgres
